### PR TITLE
Update nft.storage version to fix type URLSearchParams error

### PR DESCRIPTION
**Pull request by KishiTheMechanic**
Somehow we've got the error when using upload method.
`TypeError: Value of "this" must be of type URLSearchParams`

So I changed to use nft.storage directly and version 7.1.1 worked.

But same code didn't work with 6.4.1 (with this package.) (It's helped by rikisann on Discord.)

So I think this updating fixes the error.

We hope we can use the umi uploader because it's so helpful for us.

Thank you for the great framework team!

Have a great day☀

Best regards,
Shota Kishi

### CODE REVIEW

**Comment by lorisleiva** [comment]
Hi there, can you confirm there aren't any significant breaking changes from 6.4 to 7.1?

**Comment by lorisleiva** [comment]
Cool, I'm happy with that then. Could you run `pnpm install` locally so it also updates the lock file?

**Comment by KishiTheMechanic** [comment]
Thank you🙌

I did `pnpm install`👍

**Review by lorisleiva — APPROVED** [review]

**Comment by KishiTheMechanic** [comment]
Thank you for your reviewing and merging🙌🍻

**Pull request merged**
